# Generated by Django 3.1.1 on 2021-09-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210927_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Avatar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Nivel_Acesso',
            field=models.CharField(blank=True, choices=[('Superior', 'Superior'), ('Administrativo', 'Administrativo'), ('Representante', 'Representante')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
