# Generated by Django 3.1.1 on 2021-09-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Cadastro', models.CharField(blank=True, choices=[('Consórcio', 'Consórcio'), ('Financiamento', 'Financiamento'), ('Home Equity', 'Home Equity')], max_length=255, null=True)),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('CNPJ', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('CPF_CNPJ', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Percentual_Comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Numero_Parcelas_Comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Categoria', models.CharField(blank=True, choices=[('Supervisor', 'Supervisor'), ('Master', 'Master'), ('Junior I', 'Junior I'), ('Junior II', 'Junior II'), ('Interno', 'Interno')], max_length=255, null=True)),
                ('Tipo_Equipe', models.CharField(blank=True, choices=[('Interna', 'Interna'), ('Externa', 'Externa')], max_length=255, null=True)),
                ('Percentual_Comissao_Equipe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Numero_Parcelas_Estorno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Percentual_Comissao_Estorno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegraComissionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Regra', models.CharField(blank=True, choices=[('Antiga', 'Antiga'), ('Atual', 'Atual')], max_length=255, null=True)),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
                ('Percentual_Comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Numero_Parcelas_Comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Tempo_Acompanhamento_Estorno', models.CharField(blank=True, choices=[('1 mês', '1 mês'), ('2 mêses', '2 mêses'), ('3 mêses', '3 mêses'), ('4 mêses', '4 mêses'), ('5 mêses', '5 mêses'), ('6 mêses', '6 mêses'), ('7 mêses', '7 mêses'), ('8 mêses', '8 mêses'), ('9 mêses', '9 mêses'), ('10 mêses', '10 mêses'), ('11 mêses', '11 mêses'), ('12 mêses', '12 mêses')], max_length=255, null=True)),
                ('Percentual_Estorno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Numero_Parcelas_Estorno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Inicio_Regra', models.DateField(blank=True, null=True)),
                ('Fim_Regra', models.DateField(blank=True, null=True)),
                ('Limite_Relatorio', models.DateField(blank=True, null=True)),
                ('Administradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.administradora')),
            ],
        ),
        migrations.CreateModel(
            name='Consorcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Venda', models.CharField(blank=True, choices=[('Interna', 'Interna'), ('Externa', 'Externa')], max_length=255, null=True)),
                ('Tipo_Pessoa', models.CharField(blank=True, choices=[('Fisica', 'Fisica'), ('Juridica', 'Juridica')], max_length=255, null=True)),
                ('Grupo', models.CharField(blank=True, max_length=255, null=True)),
                ('Cota', models.CharField(blank=True, max_length=255, null=True)),
                ('Contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('Valor_Credito', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('CPF', models.CharField(blank=True, max_length=255, null=True)),
                ('RG_CNH', models.CharField(blank=True, max_length=255, null=True)),
                ('Orgao_Expedidor', models.CharField(blank=True, max_length=255, null=True)),
                ('Data_Emissao', models.DateField(blank=True, null=True)),
                ('Data_Nascimento', models.DateField(blank=True, null=True)),
                ('Telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('Celular', models.CharField(blank=True, max_length=255, null=True)),
                ('CEP', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado', models.CharField(blank=True, max_length=255, null=True)),
                ('Cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('Rua', models.CharField(blank=True, max_length=255, null=True)),
                ('Numero', models.CharField(blank=True, max_length=255, null=True)),
                ('Complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('Bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('Nome_Pai', models.CharField(blank=True, max_length=255, null=True)),
                ('Nome_Mae', models.CharField(blank=True, max_length=255, null=True)),
                ('Sexo', models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Não optar', 'Não optar')], max_length=255, null=True)),
                ('Natural_Cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('Nacionalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('Nome_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Tempo_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Profissao', models.CharField(blank=True, max_length=255, null=True)),
                ('Renda', models.CharField(blank=True, max_length=255, null=True)),
                ('CEP_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Cidade_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Rua_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Numero_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Complemento_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Bairro_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefone_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Patrimonio_Total', models.CharField(blank=True, max_length=255, null=True)),
                ('Administradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.administradora')),
                ('Representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.representante')),
            ],
        ),
    ]
