# Generated by Django 3.1.1 on 2021-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consorcio',
            name='Tipo_Pessoa',
            field=models.CharField(blank=True, choices=[('Fisica', 'Fisica'), ('Juridica', 'Juridica')], max_length=255, null=True),
        ),
    ]
