# Generated by Django 3.1.1 on 2021-09-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regracomissionamento',
            old_name='Nome',
            new_name='Nome_Regra',
        ),
    ]
