# Generated by Django 3.1.1 on 2021-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20210928_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regracomissionamento',
            name='Numero_Parcelas_Comissao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regracomissionamento',
            name='Numero_Parcelas_Estorno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='Numero_Parcelas_Comissao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='Numero_Parcelas_Estorno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
