# Generated by Django 3.1.1 on 2021-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20210927_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='regracomissionamento',
            name='Tipo_Regra',
            field=models.CharField(blank=True, choices=[('Antiga', 'Antiga'), ('Atual', 'Atual')], max_length=255, null=True),
        ),
    ]
