# Generated by Django 3.1.1 on 2021-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20210928_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='Faturamento_Mensal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='Fundacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='Inscricao_Estadual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consorcio',
            name='Razao_Social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
