# Generated by Django 3.1.1 on 2021-09-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20210927_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='Status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
