# Generated by Django 3.1.1 on 2021-09-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20210928_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Venda', models.CharField(blank=True, choices=[('Interna', 'Interna'), ('Externa', 'Externa')], max_length=255, null=True)),
                ('Tipo_Pessoa', models.CharField(blank=True, choices=[('Fisica', 'Fisica'), ('Juridica', 'Juridica')], max_length=255, null=True)),
                ('Tipo_Bem', models.CharField(blank=True, choices=[('Imóvel', 'Imóvel'), ('Automóvel', 'Automóvel')], max_length=255, null=True)),
                ('Contrato', models.CharField(blank=True, max_length=255, null=True)),
                ('Valor_Credito', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(blank=True, max_length=255, null=True)),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
                ('CPF', models.CharField(blank=True, max_length=255, null=True)),
                ('RG_CNH', models.CharField(blank=True, max_length=255, null=True)),
                ('Orgao_Expedidor', models.CharField(blank=True, max_length=255, null=True)),
                ('Data_Emissao', models.DateField(blank=True, null=True)),
                ('Data_Nascimento', models.DateField(blank=True, null=True)),
                ('Razao_Social', models.CharField(blank=True, max_length=255, null=True)),
                ('CNPJ', models.CharField(blank=True, max_length=255, null=True)),
                ('Inscricao_Estadual', models.CharField(blank=True, max_length=255, null=True)),
                ('Fundacao', models.DateField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefone', models.CharField(blank=True, max_length=255, null=True)),
                ('Celular', models.CharField(blank=True, max_length=255, null=True)),
                ('Faturamento_Mensal', models.CharField(blank=True, max_length=255, null=True)),
                ('CEP', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado', models.CharField(blank=True, max_length=255, null=True)),
                ('Cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('Rua', models.CharField(blank=True, max_length=255, null=True)),
                ('Numero', models.CharField(blank=True, max_length=255, null=True)),
                ('Complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('Bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('Nome_Pai', models.CharField(blank=True, max_length=255, null=True)),
                ('Nome_Mae', models.CharField(blank=True, max_length=255, null=True)),
                ('Sexo', models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Não optar', 'Não optar')], max_length=255, null=True)),
                ('Natural_Cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('Nacionalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('Nome_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Tempo_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Profissao', models.CharField(blank=True, max_length=255, null=True)),
                ('Renda', models.CharField(blank=True, max_length=255, null=True)),
                ('CEP_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Estado_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Cidade_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Rua_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Numero_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Complemento_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Bairro_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Telefone_Empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('Patrimonio_Total', models.CharField(blank=True, max_length=255, null=True)),
                ('Administradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.administradora')),
                ('Representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.representante')),
            ],
        ),
    ]
